### ISSUE TITLE
How to compile ffmpeg with custom codecs

### ISSUE THREAD

**Issue by gulzar1996** [madhavanmalolan/ffmpegandroidlibrary#1]
My app size is around 20mb.
 I dont need most of the codec.
 How do generate so file for the codec I need ?
Thanks for the awesome library

**Comment by madhavanmalolan** [comment]
Hi Gulzar,
Yes the app size does get bloated, since i have tried to compile all the frequently used codecs.
You can follow instructions here (Exactly what i did to build this library).

https://medium.com/madhavanmalolan/ffmpeg-for-android-b307f2613c82

You can edit the "Build Script" and disable the codecs you don't want.
