### ISSUE TITLE
Installation failed with message INSTALL_FAILED_NO_MATCHING_ABIS

### ISSUE THREAD

**Issue by bkatgithub** [madhavanmalolan/ffmpegandroidlibrary#2]
Hi,

I am not able to install on emulator (running api 25).  I get the following error

```
$ adb push /Users/bc/tmp/AndroidSandbox/app/build/outputs/apk/app-debug.apk /data/local/tmp/my.sandbox.project2
$ adb shell pm install -r "/data/local/tmp/my.sandbox.project2"
Failure [INSTALL_FAILED_NO_MATCHING_ABIS: Failed to extract native libraries, res=-113]


Error while Installing APK
```

I have specified the abi filters in my app build.gradle defaultConfig as follows

  ```
defaultConfig {
        ...
        ndk {
            abiFilters 'x86', 'x86_64', 'armeabi', 'armeabi-v7a', 'arm64-v8a'
        }
  }

  dependencies {
        ...
        compile 'com.madhavanmalolan.android:ffmpegandroidlibrary:0.0.4'
  }
```

I built my .so libs using https://github.com/IljaKosynkin/FFmpeg-Development-Kit.
And I copied them to my projects src/main/jniLibs folder.

Any idea what is causing the error?  I am running Android Studio 2.3.3, .so libs built using NDK 13rb and FFMPEG 3.2.9.

Thanks.

**Comment by bkatgithub** [comment]
The issue seems to be fixed. In src/main/jniLibs the folders for each architecture did not contain the .so files which were actually embedded one level deeper in a subfolder.  When I moved them up one level to be directly under src/main/jniLibs/x86 for example, the installation succeeded.

**Comment by madhavanmalolan** [comment]
The library currently supports only arm-v7a
You are getting this error because you have multiple ABIs configured under
ndk { }

It will work fine if you have only armeabi-v7a in the ndk section.

However if you want to support all these architectures, you can do a manual
compilation (link mentioned in the README.md)

On 11-Nov-2017 1:15 AM, "bkatgithub" <notifications@github.com> wrote:

Hi,

I am not able to install on emulator (running api 25). I get the following
error

$ adb push /Users/bc/tmp/AndroidSandbox/app/build/outputs/apk/app-debug.apk
/data/local/tmp/my.sandbox.project2
$ adb shell pm install -r "/data/local/tmp/my.sandbox.project2"
Failure [INSTALL_FAILED_NO_MATCHING_ABIS: Failed to extract native
libraries, res=-113]


Error while Installing APK

I have specified the abi filters in my app build.gradle defaultConfig as
follows

defaultConfig {
      ...
      ndk {
          abiFilters 'x86', 'x86_64', 'armeabi', 'armeabi-v7a', 'arm64-v8a'
      }
}

dependencies {
      ...
      compile 'com.madhavanmalolan.android:ffmpegandroidlibrary:0.0.4'
}

I built my .so libs using https://github.com/IljaKosynkin/FFmpeg-
Development-Kit.
And I copied them to my projects src/main/jniLibs folder.

Any idea what is causing the error?

Thanks.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/madhavanmalolan/ffmpegandroidlibrary/issues/2>, or mute
the thread
